# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "cancun"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  via-ir = false
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 999
  out = "out"
  script = "scripts"
  solc = "0.8.27"
  src = "contracts"
  test = "test"
  cache_path  = "cache_forge"
  libs = ["node_modules", "lib"]
  gas_reports_ignore = ["MockToken"]
  fs_permissions = [{ access = "read", path = "out" }, { access = "read-write", path = "artifacts" }, { access = "read", path = "node_modules" }]
  allow_paths = ["*", "/", "./node_modules/"]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[profile.coverage]
  via-ir = false

[etherscan]

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 160
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true



[rpc_endpoints]
  arbitrum = "https://arbitrum-mainnet.infura.io/v3/${api_key_infura}"
  avalanche = "https://avalanche-mainnet.infura.io/v3/${api_key_infura}"
  avalanche-fuji = "https://avalanche-fuji-c-chain-rpc.publicnode.com"
  localhost = "http://localhost:8545"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${api_key_alchemy}"
  optimism = "https://optimism-mainnet.infura.io/v3/${api_key_infura}"
  optimism-sepolia = "https://opt-sepolia.g.alchemy.com/v2/{api_key_alchemy}"
  polygon = "https://polygon-mainnet.infura.io/v3/${api_key_infura}"
  polygon-amoy = "https://polygon-amoy.drpc.org"
  sepolia = "https://sepolia.infura.io/v3/${api_key_infura}"
  gnosis = "https://gnosis-mainnet.g.alchemy.com/v2/${api_key_alchemy}"
  gnosis-chidao = "https://rpc.chiadochain.net"
  bsc-testnet = "https://bnb-testnet.g.alchemy.com/v2/${api_key_alchemy}"
  bsc = "https://bnb-mainnet.g.alchemy.com/v2/${api_key_alchemy}"
  base = "https://base-mainnet.g.alchemy.com/v2/${api_key_alchemy}"
  base-sepolia = "https://base-sepolia.g.alchemy.com/v2/${api_key_alchemy}"
  scroll-testnet = "https://rpc.ankr.com/scroll_sepolia_testnet"
  scroll = "https://scroll-mainnet.public.blastapi.io"

